name: day90
description: 90 Day App

dependencies:
  material_design_icons_flutter: 3.2.3595

  flutter_signature_pad: ^2.0.0+1
  after_layout: ^1.0.7

  #  json_serializable: ^2.1.1
#  json_annotation: ^2.1.0
#  dart_json_mapper: any
  flutter:
    sdk: flutter
  firebase_auth: 0.8.4+2
  path_provider: ^0.5.0+1
  firebase_core: ^0.3.0
  firebase_database: ^2.0.3
  shared_preferences: ^0.5.2
  firebase_storage: ^2.0.0
  google_sign_in: ^4.0.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
#  build_runner: any
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/Resilience_Aviation_Logo.jpg
    - images/google_logo.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
